[phases.setup]
nixPkgs = ['nodejs-18_x', 'ffmpeg']

[phases.install]
cmds = [
  'npm install',
  'cd /app/server && npm install',
  'cd /app/client && npm install'
]

[phases.build]
cmds = ['cd /app/client && npm run build']

[start]
cmd = 'cd /app/server && node index.js'

